[window]
padding.x = 12
padding.y = 12
[font]
size = 9.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[general]
import = [
    "~/.config/alacritty/themes/gruvbox_hard.toml"
]
