include colors

gaps inner 0
gaps outer 0

default_border pixel 0

focus_follows_mouse no

set $gnome-schema org.gnome.desktop.interface
exec_always {
    gsettings set $gnome-schema gtk-theme 'Adwaita'
    gsettings set $gnome-schema color-scheme 'prefer-dark'
    gsettings set $gnome-schema cursor-theme 'volantes_cursors'
}

client.focused           $blue     $base        $text      $blue      $blue
client.focused_inactive  $mantle   $base        $text      $mantle    $mantle
client.unfocused         $mantle   $base        $text      $mantle    $mantle
client.urgent            $peach    $base        $peach     $overlay0  $peach
client.placeholder       $base     $base        $text      $overlay0  $overlay0
client.background        $base
