bindsym $mod+Shift+c exec --no-startup-id $browser "https://calendar.google.com/"
bindsym $mod+Shift+A exec --no-startup-id $browser "https://chatgpt.com/"
bindsym $mod+Shift+G exec --no-startup-id $browser "https://gmail.com"
