#!/bin/bash

SERVICES="nginx mariadb php-fpm"

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

case "$1" in
    start)
        echo -e "${GREEN}Starting LEMP Stack...${NC}"
        sudo systemctl start $SERVICES
        echo -e "${GREEN}Services started.${NC}"
        ;;
    stop)
        echo -e "${RED}Stopping LEMP Stack...${NC}"
        sudo systemctl stop $SERVICES
        echo -e "${RED}Services stopped.${NC}"
        ;;
    restart)
        echo -e "${YELLOW}Restarting LEMP Stack...${NC}"
        sudo systemctl restart $SERVICES
        echo -e "${GREEN}Services restarted.${NC}"
        ;;
    status)
        echo -e "${YELLOW}Checking Status...${NC}"
        sudo systemctl status $SERVICES --no-pager | grep "Active:"
        ;;
    *)
        echo "Usage: lemp {start|stop|restart|status}"
        exit 1
        ;;
esac
